title:            Ryan Wood
description:      Unclear Thoughts on Software Development
url:              # Site url.
signoff:          Ryan
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-3709570-8
share: y

links:
  - name:         About
    url:          /
  - name:         Blog
    url:          /blog
  - name:         Archives
    url:          /archives
  - name:         GitHub
    url:          http://github.com/ryanwood
    external:     true
  - name:         Twitter
    url:          http://twitter.com/ryanwood
    external:     true
  - name:         LinkedIn
    url:          http://github.com/ryanwood
    external:     true
  - name:         Email
    url:          mailto:hello@ryanwood.com
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
